### ISSUE TITLE
About The Game Example.7z

### ISSUE THREAD

**Issue by Ahmed-Dzair-Dev** [CableDorado2/Ikemen-Plus-Ultra#20]
Is it the source code ? What IDE you suggest ?

Code::Blocks ?
Qt Creator ?
Vs Codium ?
Geany ?
Vs code ?

I am a linux user .

**Comment by Ahmed-Dzair-Dev** [comment]
I like code blocks and qt creator because they have a good debuger and because its low in use resources .

**Comment by Ahmed-Dzair-Dev** [comment]
I have tried the Ultimate Tetera  "The Mugen for linux Code Blocks project " but when i done compiling and debuging and fixing issues . 

It give me the excutable "ut" wich is the game with a messsage apeared on the terminal with a another langauge i didnt deal with it ever.

N�o foi poss�vel carregar a fonte padr�o!
=============================================
  carregando select.txt... 
=============================================
Nao foi possivel carregar o arquivo de animacoes
Nao foi possivel abrir o arquivo

Sorry for my bad english.

**Comment by CableDorado2** [comment]
> Is it the source code ? What IDE you suggest ?
> 
> Code::Blocks ? Qt Creator ? Vs Codium ? Geany ? Vs code ?
> 
> I am a linux user .

Hi! first of all. Thanks by test this engine and may I ask, what exactly are you trying to do? I understand that you want to compile the source code in Linux, but do you want to compile an executable for Linux just to run everything else there, for example? I mean, something like [Ikemen GO](https://github.com/ikemen-engine/Ikemen-GO)

You can find the current source code in main branch/src folder.

Like I put in [Tools Section](https://github.com/CableDorado2/Ikemen-Plus-Ultra/tree/main?tab=readme-ov-file#tools), I suggest **Visual C++ 2010 Express** to compile this src code, because the source code was generated from there and so far there is no Linux version (I still don't know how to compile a linux or even MacOS executables).

Let me explain, a long time ago I found this source code and incorporated it into the improvements that I am doing for the engine. However, I still don't know what is needed to generate an executable for Linux and if it is possible to do it from Windows using Visual C++.
